Feature/map
Peace-Research-Institute-Frankfurt/websites pull request #273
Opened 2023-09-15 08:32 UTC by cKehres

2023-09-15 08:41 UTC, awesomephant commented
Hi @cKehres, der Build schlägt noch fehl, aber ich glaube da fehlen nur ein paar Abhängigkeiten in der `package.json` (`@visx` und `csv-loader`) - könnt ihr die noch hinzufügen?

2023-09-25 12:46 UTC, awesomephant commented
@cKehres Danke für den Fix, jetzt beschwert er sich über die fehlenden Imports eurer Komponenten in `src/components/PrintPostBody.js` - könnt ihr das beheben?

2023-09-25 13:00 UTC, cKehres commented
@awesomephant Mit dem Error der da jetzt ist kann ich ad hoc nichts mit anfangen, kannst mir nen hint geben?

2023-11-15 10:47 UTC, awesomephant commented
@cKehres Hier das Problem, das ich Montag erwähnt hatte:

Es sieht so aus, als würde jeder `<CountryStatisticsLayer>` alle Länder zeichnen, nicht nur die, die farblich markiert sind. Das macht die Datei größer und sieht etwas komisch aus (sichtbar in Firefox). Wenn man die Datei herunterläd und in Illustrator öffnet kann man sehen, das es drei Kopien von jedem Land gibt:

![image](https://github.com/Peace-Research-Institute-Frankfurt/websites/assets/2758247/8a4480cf-69c0-457c-941d-a4013dd75d3a)

Können wir das beheben?

2023-11-17 14:38 UTC, awesomephant commented on e-learning/src/components/CountryStatisticsLayerCountries.js
Hier wäre es gut, wenn wir `projection.features` _vor_ der Render-Schleife filtern könnten, damit nur die eingefärbten Länder gerendert werden, nicht alle.

2023-11-17 14:41 UTC, awesomephant requested changes
In `CountryStatisticsLayerCountries` sollten wir `projection.features` vor der Render-Schleife filtern, damit nur die eingefärbten Länder gerendert werden, nicht alle. Anonsten 👍

2023-11-19 22:48 UTC, cKehres commented
@awesomephant Hier sind in den Tests sehr viele Dependencies die nicht passen. Beim mergen wurden die package Dateien teilweise komplett neu angelegt. Ich sehe nicht warum er hier nicht durchläuft, das sind Bereiche wo wir nie dran waren. Eine Idee?

2023-11-21 15:13 UTC, awesomephant commented
@cKehres Ja, der beschwert sich, das die neuen Komponenten in unserem Print-Template (`src/components/PrintPostBody.js`) nicht vorhanden sind - wir hatten das gleiche Problem mit dem Map-Komponenten. Am besten fügst du einfach Stubs ein, wie ich es hier gemacht habe:

https://github.com/Peace-Research-Institute-Frankfurt/websites/blob/49b9c857b5c2b9729219a29f0091269eb953f1dd/e-learning/src/components/PrintPostBody.js#L54-L56

(Das Problem tritt immer erst im Build auf, weil die Print-PDFs im Dev-Modus nicht gebaut werden)

2024-02-19 11:20 UTC, cKehres commented
tests laufen nicht durch aufgrund der Meldung
Cannot find module 'dayjs/plugin/customParseFormat' from '../node_modules/exceljs/lib/csv/csv.js'

Dies scheint aus dem accessibility-checker zu kommen weil dieser exceljs als dependency aufführt, wir haben den origin main Branch integriert, müsste also auch im main eigentlich nicht durchlaufen.

2024-02-19 18:08 UTC, awesomephant commented
@cKehres okay, den Test können wir hier ignorieren, da kümmere ich mich drum. Die Dokumentation ist auch durchgekommen, das einzige Problem ist dieses:

![Screenshot Agenturt](https://github.com/Peace-Research-Institute-Frankfurt/websites/assets/2758247/14dd8f9a-4881-4686-a86e-fc40868efac6)

Alle Grafiken zeigen Scrollbalken und sind etwas angeschnitten. Plattform ist Windows 10, Firefox und Chrome. Könnt ihr das reproduzieren/reparieren? Dann sind wir bereit, das ganze Ding abzunehmen.

2024-02-20 09:25 UTC, awesomephant commented
Nachtrag: Browser-Versionen für das og Problem sind:

- Firefox 122.0.1 (64-Bit)
- Edge 121.0.2277.128 (64-Bit)
- Chrome 121.0.6167.185 (64-Bit)

2024-03-11 16:11 UTC, cKehres commented
@awesomephant Die Scrollbalken sind nun nur sichtbar wenn diese von Nöten sind.

2024-03-12 09:20 UTC, awesomephant commented
@cKehres LGTM 👍

2024-03-12 09:26 UTC, merged